### ISSUE TITLE
Cannot Add to My CubeMX.

### ISSUE THREAD

**Issue by muaxiaohei** [QuantumLeaps/cmsis-packs#1]
![image](https://github.com/user-attachments/assets/b4503356-a0c6-469a-bd4b-d0ba8cf83a39)

Try， But always with error.

**Comment by muaxiaohei** [comment]
![image](https://github.com/user-attachments/assets/c7b28e12-6110-4706-9523-ee9f3cd6e71a)

**Comment by quantum-leaps** [comment]
The URL shown in the [YouTube video](https://youtu.be/M05jMX3_wJk?si=wA8gLFGPozFiioFx) is:

https://raw.githubusercontent.com/QuantumLeaps/cmsis-packs/main/QuantumLeaps.pidx

You seem to have something else. Please try the one above.

--MMS

**Comment by muaxiaohei** [comment]
Thanks for your reply, but it seems to have failed again. Is it related to my network? But I can use CubeMX to update my packages.
![image](https://github.com/user-attachments/assets/ff25749a-d7ab-4cb5-86c4-898677c21f86)

**Comment by quantum-leaps** [comment]
The URL works for me (see attached screenshot). I'm not sure how to help if I can't reproduce the problem.
--MMS
![QuantumLeaps-packs](https://github.com/user-attachments/assets/81c361fe-fed9-4318-8952-96968f6cb941)

**Comment by muaxiaohei** [comment]
I will try later since it's 2.21am now at my locations. 
I will check my network, and try to reinstall my cubemx.
sincere thanks.
;)

**Comment by quantum-leaps** [comment]
But there are other ways to get the QuantumLeaps packages. You can try:
1. download the pack from https://github.com/QuantumLeaps/qpc/releases/download/v7.3.4/QuantumLeaps.qpc.7.3.4.pack
2. use the "From Local..." button in the Embedded Software Packages Manager

**Comment by muaxiaohei** [comment]
Thanks, This is what I need.😂
